### ISSUE TITLE
[JOSS] AUTHORS file

### ISSUE THREAD

**Issue by sidihamady** [cire-thk/BifacialSimu#16]
Please add an AUTHORS file to the repo, with the list you gave in Readme.md, with their contribution.
They can also be added in the acknowledgements section.

[https://github.com/openjournals/joss-reviews/issues/4443#issuecomment-1158667882](https://github.com/openjournals/joss-reviews/issues/4443#issuecomment-1158667882)

**Comment by EwaGomez** [comment]
Thank you for your suggestion! I already mentioned the students in the Acknowledgement section "A special thanks to all the students of the University of Applied Sciences Cologne who have contributed so far to this project, it would not have been as successful without their input." - BifacialSimu is part of my Dissertation and research and there are many students projects helping to develop it further - all are supervised by me very closly. Do you still think I should add an authors file additionally to the Readme?

**Comment by sidihamady** [comment]
Dear @EwaGomez, in my opinion, a participant is not an author if his contribution was only to test/debug the software, without having had a contribution in the design and actual writing of the code. In this case, he/she is thanked in the Acknowledgements section. Otherwise, he is considered co-author of the software. My colleague @kanderso-nrel can give us his opinion. In any case, you are the major author of the code and after this clarification I will validate the point "Contribution and authorship".

**Comment by kanderso-nrel** [comment]
Perhaps the distinction between authors of the paper and authors of the code is relevant here.  JOSS provides guidance on the former:
- https://joss.readthedocs.io/en/latest/submitting.html#authorship
- https://joss.readthedocs.io/en/latest/review_criteria.html#authorship

I don't have any objection to the authors list currently in the paper.  As for a separate AUTHORS file in the repository: I think a list that must be updated manually is more work and more likely to be neglected than GitHub's built-in contributor tracking feature is.  However it is nice in some cases to be able to list specific contributions, or in case you want to define a "contributor" more broadly than GitHub does.  Regardless I don't feel strongly about whether such a file should be created in this case.
