### ISSUE TITLE
[JOSS] egg-info should be removed

### ISSUE THREAD

**Issue by kanderso-nrel** [cire-thk/BifacialSimu#19]
The repository currently has a `BifacialSimu.egg-info` directory.  I suggest deleting it (and potentially adding it to the `.gitignore`) since it is an artifact of the build and not actually part of the repository's source code. 

Cross-reference: https://github.com/openjournals/joss-reviews/issues/4443

**Comment by EwaGomez** [comment]
Thank you! 
We solved this issue in the latest push.
